description: This component authenticates with the Google Sheets API using the Google
  API Python client and the provided service account credentials (preferably supplied
  as an environment variable or a JSON file). Returns the authenticated service object.
name: AuthenticateGoogleSheetsAPI
parameters:
  api_version: v4
  scope: https://www.googleapis.com/auth/spreadsheets
