description: 'This component receives the list of Twitter handles and the TwitterCredentials.
  It uses the Tweepy library to fetch the last tweet from each handle and returns
  a list of dictionaries with the format {''handle'': handle, ''tweet'': last_tweet}.
  Inputs come from the Workflow InitialData.'
input-class: TwitterCredentials
name: FetchLastTweets
output-class: FetchLastTweetsInputDict
parameters: {}
